### ISSUE TITLE
Flicker (shadow)

### ISSUE THREAD

**Issue by Klemci** [RyanJGray/aliasIsolation#26] opened 2024-02-09 18:33 UTC
On a 4070ti at 90FPS 1440p,
i only tried the ASI version once, at the same time i managed to load it aside 3DMigoto (d3d11Hooked.dll renamed).
I use the HBAO+ bits 0x00060000 (very subtle) DX10/11, and ingame option OFF.

In the station to get "train", i seen the roof verry glitchy, so i reverted to EPIC build (working good with GOG version).

**Comment by Klemci** [comment] 2024-02-12 08:56
1.1.1 looks allright btw.

**Comment by RyanJGray** [comment] 2024-03-13 10:00
Yeah... I have a good idea what causes this (optimisations that I made in 1.1.2 to try and speed up some unusually slow math operations which was severely harming frame rates), turns out it breaks the shadows in some scenes! :sweat_smile:

I've got some spare time now to work on this, I'll see if I can get an update pushed out to fix this issue this week.

**Comment by RyanJGray** [comment] 2024-03-14 12:19
Going to close this as a duplicate of #21, but it will be addressed, don't worry!

**Closed as not planned** 2024-03-14 12:19 UTC
Labels: bug
