### ISSUE TITLE
Proton not working

### ISSUE THREAD

**Issue by brianx87** [RyanJGray/aliasIsolation#11] opened 2022-12-16 19:36 UTC
The injector doesn't seem to be working on Linux/SteamOS using the winedlloverride, or at the least using delete key doesn't open the dialog box. wimmn isn't a dll I've had much success getting working.

**Comment by RyanJGray** [comment] 2022-12-16 20:58
Hey there, thanks for checking out the mod!

Another user had better luck renaming the `winmm.dll` to `d3d11.dll`, perhaps you could try that?
Then, if you change your `winedlloverride` to target `d3d11` instead of `winmm`, it should work.

I'm working on an update at the moment. I'm going to just rename it to `d3d11` from now on, as it seems to be more reliable for people.

**Comment by brianx87** [comment] 2022-12-16 21:19
It's working but booting with multiple syntax and graphical errors but I'm using a modded version of the game with improved graphics settings and ReShade so I'll have to test it on a vanilla version to see if the conflicts are with my version.

**Comment by RyanJGray** [comment] 2022-12-16 22:14
Interesting, when you say syntax errors, did they mention issues with compiling shaders?

Do you get syntax and graphical errors when you only play the game, with the improved graphics settings and Reshade?

I had a problem like that, I think the Cinematic Tools part of the mod could cause issues like that, specifically on Proton.
Seems to be the way those kinds of mods compile shaders on the go.

I'd need to do further testing again, as Proton versions have moved on a lot since I last tried it.

Let me know if it still happens with vanilla (or without Reshade).
I'm curious if there's some conflict happening, specifically with Proton.

**Comment by brianx87** [comment] 2022-12-16 23:03
Nothing about shaders appears, syntax errors are appearing on a vanilla install without graphical issues, the errors are popping up and preventing the menu and game from loading, the injector GUI has only been available to me on the main menu so far. Loading only continues after several of these error dialog have been closed but they keep opening during loading.

This one appears several times
`<anonymous>:2:34: E5000: syntax error, unexpected '(', expecting ';' or ','`

followed by
`<anonymous>:29:52 E5000: syntax error, unexpected '(', expecting ';' or ','`

`<anonymous>:31:1: E5017: Aborting due to not yet implemented feature: Ternary operator. <anonymous>:48:12: E5005: Method 'GetDimensions' is not yet defined on type 'Texture2D<float3>`

`<anonymous>:6:52: E5000: syntax error, unexpected '(', expecting ';' or ','`

EDIT: Got in game and it's nothing but a grey screen with various UI elements loading in when pressing buttons.

**Comment by RyanJGray** [comment] 2022-12-18 12:52
> Nothing about shaders appears, syntax errors are appearing on a vanilla install without graphical issues, the errors are popping up
> 
> This one appears several times
> `<anonymous>:2:34: E5000: syntax error, unexpected '(', expecting ';' or ','`
> 
> followed by
> `<anonymous>:29:52 E5000: syntax error, unexpected '(', expecting ';' or ','`
> 
> `<anonymous>:31:1: E5017: Aborting due to not yet implemented feature: Ternary operator. <anonymous>:48:12: E5005: Method 'GetDimensions' is not yet defined on type 'Texture2D<float3>`
> 
> `<anonymous>:6:52: E5000: syntax error, unexpected '(', expecting ';' or ','`

Did some testing locally and was able to reproduce those messages. Thanks!

It's because of how the mod compiles the shaders. It compiles them at run-time, which Wine (and by extension Proton) doesn't seem to have fully implemented.
Microsoft doesn't recommend compiling shaders like that anyway, so I've made some changes to fix this for Proton users (I precompile the shaders when I make a release now).

There'll be a new release out today with this fixed :D

**Comment by RyanJGray** [comment] 2022-12-19 01:21
This should be fixed in the latest release, I no longer get the shader errors popping up on Proton.

Could you give the latest release a go, and see if you still run into the same issue?

**Comment by brianx87** [comment] 2022-12-19 05:32
> This should be fixed in the latest release, I no longer get the shader errors popping up on Proton.
> 
> Could you give the latest release a go, and see if you still run into the same issue?

What's the new install method for proton?

**Comment by brianx87** [comment] 2022-12-19 16:37
Works great!

**Comment by RyanJGray** [comment] 2022-12-19 18:46
Great to hear! Let me know if you run into any other issues.
Enjoy! :D

**Closed as completed by RyanJGray** 2022-12-19 18:46 UTC
Labels: bug, proton only
